hanaro-3rd/backend

build.gradle
src/main/java/com/example/travelhana/Config/SwaggerConfig.java
src/main/java/com/example/travelhana/TravelhanaApplication.java

스웨거 설정 
url 포트번호 뒤에 
`/swagger-ui.html`
붙히면 스웨거 페이지로 이동합니다.

Chore: 스웨거 설정

---

src/main/java/com/example/travelhana/Config/CustomAuthorizationFilter.java
src/main/java/com/example/travelhana/Config/SecurityConfig.java
src/main/java/com/example/travelhana/TravelhanaApplication.java

휴대폰 인증코드 전송과 인증코드 입력 시 일치 여부를 확인하는 API를 Spring Security 필터에서 제외
"/verification" , "/verification/auth" 를 포함한 url은 Request Filter에서 제외됩니다.
- `CustomAuthorizationFilter`에 제외 url 리스트에 위 두 url을 추가했습니다.
- `SecurityConfig`에 두 url에 대한 권한을 허가해줬습니다.

Refactor: 휴대폰 인증 관련 url 필터에서 제외

---

src/main/java/com/example/travelhana/Service/implement/ExchangeServiceImpl.java

Refactor: api로 환율 호출시 시간정보 추가

---

src/main/java/com/example/travelhana/Domain/Account.java
src/main/java/com/example/travelhana/Domain/Category.java
src/main/java/com/example/travelhana/Domain/CategoryPlan.java
src/main/java/com/example/travelhana/Domain/ExchangeHistory.java
src/main/java/com/example/travelhana/Domain/ExchangeRate.java
src/main/java/com/example/travelhana/Domain/ExchangeReservation.java
src/main/java/com/example/travelhana/Domain/ExternalAccount.java
src/main/java/com/example/travelhana/Domain/Keymoney.java
src/main/java/com/example/travelhana/Domain/Marker.java
src/main/java/com/example/travelhana/Domain/PaymentHistory.java
src/main/java/com/example/travelhana/Domain/Plan.java
src/main/java/com/example/travelhana/Domain/User.java
src/main/java/com/example/travelhana/Domain/UserToMarker.java
src/main/java/com/example/travelhana/Repository/ExternalAccountRepository.java
src/main/java/com/example/travelhana/Service/implement/AccountServiceImpl.java
src/main/java/com/example/travelhana/Service/implement/UserServiceImpl.java

Refactor: 외부 계좌 불러올 시 이미 연결된 계좌 제외

Refactor: 외부 계좌 불러올 시 이미 연결된 계좌 제외

---

src/main/java/com/example/travelhana/Service/implement/PlanServiceImpl.java

Refactor: 카테고리별 경비계획 시 결제내역 단위 추가

Refactor: 카테고리별 경비계획 시 결제내역 단위 추가

---

src/main/java/com/example/travelhana/Config/CustomAuthorizationFilter.java

Chore: ssl 필터 제외

---

src/main/java/com/example/travelhana/Domain/ExternalAccount.java
src/main/java/com/example/travelhana/Dto/Account/AccountDummyDto.java
src/main/java/com/example/travelhana/Dto/Marker/MarkerPickUpResultDto.java
src/main/java/com/example/travelhana/Repository/ExternalAccountRepository.java
src/main/java/com/example/travelhana/Service/implement/AccountServiceImpl.java
src/main/java/com/example/travelhana/Service/implement/MarkerServiceImpl.java
src/main/java/com/example/travelhana/Service/implement/UserServiceImpl.java

Refactor: 외부 계좌 연결 로직 및 마커 줍기 리턴값 변경

Refactor: 외부 계좌 연결 로직 및 마커 줍기 리턴값 변경

---

src/main/java/com/example/travelhana/Config/CustomAuthProvider.java
src/main/java/com/example/travelhana/Config/CustomAuthorizationFilter.java
src/main/java/com/example/travelhana/Config/SecurityConfig.java

Test: Jenkins 테스트

---

src/main/java/com/example/travelhana/Dto/Authentication/PhonenumResponseDto.java

Test: jenkins 테스트4

---

src/main/java/com/example/travelhana/Dto/Authentication/RoleToUserRequestDto.java

Test: jenkins 테스트5

---

src/main/java/com/example/travelhana/Controller/MarkerController.java

Test: jenkins 테스트6

---

src/main/java/com/example/travelhana/Controller/MarkerController.java

Test: jenkins 테스트8

---

src/main/java/com/example/travelhana/Dto/ResponseDto.java

Test: jenkins 테스트9

---

src/main/java/com/example/travelhana/Exception/Handler/BusinessExceptionHandler.java

Test: jenkins 테스트10

---

src/main/java/com/example/travelhana/Service/implement/AccountServiceImpl.java

Test: jenkins 테스트11

---

src/main/java/com/example/travelhana/Exception/Code/ErrorCode.java

Refactor: 401 에러 코드 수정

---

src/main/java/com/example/travelhana/Service/implement/ExchangeServiceImpl.java

환율정보를 캐싱하는 로직인 getExchangeFromRedis()를 수정했습니다.
redis에서 환율 정보를 읽어올 때 pop하는 방식에서 range 후 파싱하는 로직으로 변경했습니다.

Refactor: 환율 캐싱 로직 수정

---

.gitignore
src/main/resources/application.properties

Chore: application properties 추가

---

src/main/java/com/example/travelhana/Service/implement/UserServiceImpl.java

Test: jenkins 테스트12

---

src/main/java/com/example/travelhana/Service/implement/UserServiceImpl.java

Test: jenkins 테스트13

---

src/main/java/com/example/travelhana/Service/implement/PhoneAuthServiceImpl.java

Test: jenkins 테스트14

---

src/main/java/com/example/travelhana/Util/HolidayUtil.java

Test: jenkins 테스트15

---

src/main/java/com/example/travelhana/Util/HolidayUtil.java

Test: jenkins 테스트16

---

src/main/java/com/example/travelhana/Util/HolidayUtil.java

Test: jenkins 테스트17

---

src/main/java/com/example/travelhana/Util/HolidayUtil.java

Test: jenkins 테스트18

---

src/main/resources/application.properties

Test: jenkins 테스트19

---

src/main/java/com/example/travelhana/Service/implement/MarkerServiceImpl.java

Test: jenkins 테스트20

---

src/main/java/com/example/travelhana/Controller/MarkerController.java

Test: jenkins 테스트21

---

src/main/java/com/example/travelhana/Service/implement/PhoneAuthServiceImpl.java

Test: jenkins 테스트22

---

src/main/java/com/example/travelhana/Util/ExchangeRateUtil.java

Test: jenkins 테스트23

---

src/main/java/com/example/travelhana/Util/CryptoUtil.java

Test: jenkins 테스트24

---

src/main/java/com/example/travelhana/TravelhanaApplication.java

Test: jenkins 테스트25

---

src/main/java/com/example/travelhana/Service/implement/ExchangeServiceImpl.java

외화에서 원화로 환전 시 환전 최소금액에 대한 제한을 없앴습니다.
키머니에 있는 외화 전부를 원화로 환전할 때 최소 금액 유효성 조건이 불필요하다고 판단 후 해당 제한을 삭제합니다.

#6 Refactor: 외화에서 원화로 환전할 때 환전 최소금액 삭제

---

src/main/java/com/example/travelhana/Controller/MarkerController.java
src/main/java/com/example/travelhana/Domain/Marker.java
src/main/java/com/example/travelhana/Dto/Marker/MarkerDummyDto.java
src/main/java/com/example/travelhana/Dto/Marker/MarkerResultDto.java
src/main/java/com/example/travelhana/Exception/Code/ErrorCode.java
src/main/java/com/example/travelhana/Repository/MarkerRepository.java
src/main/java/com/example/travelhana/Service/MarkerService.java
src/main/java/com/example/travelhana/Service/implement/MarkerServiceImpl.java

Feat: 마커 리스트 정렬 및 필터 기능 추가
- API METHOD가 GET 에서 POST로 바뀌었습니다.
- REQUEST에 쿼리로 화폐코드(unit), 주운여부(isPickup), 정렬(sort)이 추가되었습니다.
- REQUEST에 바디로 현재 위치(lat, lng) 값이 추가되었습니다.
- RESPONSE에 거리값(distance)이 추가되었습니다.
- RESPONSE에 주소값(address)이 추가되었습니다.

Feat: 마커 리스트 정렬 및 필터 기능 추가

---

src/main/java/com/example/travelhana/Domain/Plan.java
src/main/java/com/example/travelhana/Service/implement/PlanServiceImpl.java

Fix: 계획 수정 총 금액 변경안되는 문제 수정

---

src/main/java/com/example/travelhana/Service/implement/ExchangeServiceImpl.java

원화에서 외화로 환전할 때 각 화폐 별 최소 환전 금액 검사를 삭제했습니다.

Refactor: 원화에서 외화 환전 시 최소환전금액 조건 삭제

---

src/main/java/com/example/travelhana/Config/CustomFailureHandler.java
src/main/resources/application.properties

로그인 실패 시 forbidden을 나타내기 위해 상태코드를 403으로 리턴합니다.

Refactor: 로그인 실패시 에러코드 변경

---

src/main/java/com/example/travelhana/Service/implement/UserServiceImpl.java

Fix: 패턴 NOT NULL 오류 제거

---

src/main/resources/application.properties

Chore: 서버 포트 설정 변경

---

src/main/java/com/example/travelhana/Config/CustomAuthorizationFilter.java
src/main/java/com/example/travelhana/Config/SecurityConfig.java
src/main/java/com/example/travelhana/Controller/MessageController.java
src/main/java/com/example/travelhana/Dto/Notification/NotificationResponseDto.java
src/main/java/com/example/travelhana/Service/NotificationService.java
src/main/java/com/example/travelhana/Service/implement/NotificationServiceImpl.java
src/main/resources/application.properties

테스트용 알림을 삽입하기 위해 알림 추가 api와 모든 알림을 불러오는 api를 구현했습니다.
- "/notification"으로 POST요청을 하면 알림을 추가할 수 있습니다. 추가된 알림은 db에 저장되고 즉시 채널아이디를 구독중인 클라이언트들에게 전송됩니다.
- "/notification"으로 GET 요청을 하면 모든 알림 리스트를 불러옵니다.

Refactor: 알림 추가 및 전체 알림 불러오기 API 구현

---

src/main/java/com/example/travelhana/Controller/UserController.java
src/main/java/com/example/travelhana/Dto/Authentication/CodeRequestDto.java
src/main/java/com/example/travelhana/Dto/Authentication/CodeResponseDto.java
src/main/java/com/example/travelhana/Service/UserService.java
src/main/java/com/example/travelhana/Service/implement/PhoneAuthServiceImpl.java
src/main/java/com/example/travelhana/Service/implement/UserServiceImpl.java

휴대폰 인증 후 기기의 존재여부도 함께 리턴합니다.
isDeviceExist, isExistUser에 따라 true, false를 담고 이에 따라 회원가입, 비밀번호 변경, 기기 업데이트 등의 로직을 수행합니다.
- 필요한 주석을 추가하고 ErrorResponse를 직접 던지는 부분을 수정했습니다.
- 기기 업데이트와 회원가입 수행 시 동일한 디바이스 아이디를 가진 데이터는 디바이스아이디와 리프레시 토큰을 null 처리합니다.

Refactor: 휴대폰 인증 후 기기 존재여부
